### ISSUE TITLE
Evaluation failed: TypeError: Cannot read properties of undefined (reading 'LegacyPhoneFeatures')

### ISSUE THREAD

**Issue by sonkase** [pascalroget/whatsgpt#12]
I get the error:
Error: Evaluation failed: TypeError: Cannot read properties of undefined (reading 'LegacyPhoneFeatures')
    at __puppeteer_evaluation_script__:13:76
    at ExecutionContext._evaluateInternal (...\whatsgpt\node_modules\whatsapp-web.js\node_modules\puppeteer\lib\cjs\puppeteer\common\ExecutionContext.js:221:19)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async ExecutionContext.evaluate (...\whatsgpt\node_modules\whatsapp-web.js\node_modules\puppeteer\lib\cjs\puppeteer\common\ExecutionContext.js:110:16)
    at async Client.initialize (...\whatsgpt\node_modules\whatsapp-web.js\src\Client.js:267:9)
    
Do you have any idea why this happens?
Thanks in advance

**Comment by Rohit-Ranjan-Nilkant** [comment]
Go to node_modules -->whatsapp-web.js --> src -->util ---> Injected.js 
and comment out this window.Store.Features = window.mR.findModule('FEATURE_CHANGE_EVENT')[0].LegacyPhoneFeatures; (Line 16)
